# Generated by Django 5.1.4 on 2025-02-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='specialization',
            field=models.CharField(choices=[('PT', 'Personal Trainer'), ('NT', 'Nutritionist'), ('PS', 'Psychologist'), ('PH', 'Physical Therapist'), ('NU', 'Nutritional Therapist'), ('DI', 'Dietician')], max_length=2),
        ),
    ]
