# Generated by Django 5.1.4 on 2025-02-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_serviceprovider_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='certifications',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
    ]
