# Generated by Django 5.1.4 on 2025-02-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_package_duration_months_alter_package_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='experience_years',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='qualifications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
