# Generated by Django 5.1.4 on 2025-02-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_serviceprovider_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='bio_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
