# Generated by Django 5.1.4 on 2025-02-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_serviceprovider_bio_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
    ]
